### ISSUE TITLE
Smooth waves shader at high zooms

### ISSUE THREAD

**Issue by sensescape** [tangrams/refill#5]
@bcamper @patriciogonzalezvivo 
Why is the shader not smooth at z17?

Here's how it looks at z15
<img width="161" alt="screen shot 2016-02-09 at 5 01 20 pm" src="https://cloud.githubusercontent.com/assets/466585/12936015/2d6c5600-cf4f-11e5-845b-d61cdf33ca76.png">

At z17 the edges look rough and uneven:
<img width="303" alt="screen shot 2016-02-09 at 5 04 30 pm" src="https://cloud.githubusercontent.com/assets/466585/12936023/3c1c2716-cf4f-11e5-926a-e136e661311f.png">

**Comment by sensescape** [comment]
<img width="279" alt="screen shot 2016-02-09 at 5 17 59 pm" src="https://cloud.githubusercontent.com/assets/466585/12936199/1a7fdb8c-cf51-11e5-824e-8e976cc86e31.png">

**Comment by sensescape** [comment]
at z19
<img width="416" alt="screen shot 2016-02-10 at 10 39 43 am" src="https://cloud.githubusercontent.com/assets/466585/12957656/aa16bee6-cfe2-11e5-8105-ae9ad0356a71.png">

**Comment by bcamper** [comment]
@patriciogonzalezvivo ?

**Comment by patriciogonzalezvivo** [comment]
The problem is on this line: https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L691 commenting it will "solve" the problem... but also will hook the wave line pattern to screen coordinates. 
Before jumping and find a better strategy for this I have some questions:
- I saw that you have 3 different wave stripes patters `waves`, `waves2` and `stream-waves`. What are the differences between them? 

i think we should start working in a more modular structure for the shaders... so we can re-use the modules (https://github.com/tangrams/tangram-sandbox/tree/gh-pages/modules/space) I made and fix this kind of behavior fewer times. That will be ok?

<img width="1508" alt="screen shot 2016-02-12 at 9 11 04 am" src="https://cloud.githubusercontent.com/assets/346914/13009131/a82bf42a-d168-11e5-9fb0-de23a7744784.png">
<img width="1504" alt="screen shot 2016-02-12 at 9 10 55 am" src="https://cloud.githubusercontent.com/assets/346914/13009132/a82e4b9e-d168-11e5-9eb7-974d43e6a344.png">

**Comment by sensescape** [comment]
waves and waves 2  are basically the same, waves 2 is just slightly darker. I wanted to have more contrast between ground and water at higher zooms. 
I'm using waves up to z13, then it gets darker at z13 and up with waves2

stream-waves are used for the river lines:
<img width="589" alt="screen shot 2016-02-10 at 3 43 33 pm" src="https://cloud.githubusercontent.com/assets/466585/13016356/1a407108-d173-11e5-85e0-8107e4d0cd9e.png">

Yes, modular structure sounds good! Thanks!

**Comment by bcamper** [comment]
@patriciogonzalezvivo could you help with modularization? Basically structure it so we can pull some of the reusable bits out into other files, once we have file include functionality.

**Comment by patriciogonzalezvivo** [comment]
working on it

**Comment by patriciogonzalezvivo** [comment]
I have simplify version of it here: http://tangrams.github.io/tangram-play/?scene=https://gist.githubusercontent.com/anonymous/bfcf61663b6bc183d284/raw/6a820cc0a4d84266b753a3b00f17cedcc5e7ab8b/scene.yaml

Need some fine tunning... Should I merge it @sensescape ?? or you want to do it after doing the adjustments?

**Comment by sensescape** [comment]
ok merge. Thanks @patriciogonzalezvivo !

**Comment by patriciogonzalezvivo** [comment]
Let me know if you need assistance with it : )

**Comment by patriciogonzalezvivo** [comment]
Do I merge or you?

**Comment by sensescape** [comment]
you can merge

**Comment by patriciogonzalezvivo** [comment]
Done, can you check everything looks ok?

**Comment by sensescape** [comment]
waves pattern looks great! 

but the coast stripes got thicker in line width.

previous:
<img width="344" alt="screen shot 2016-02-12 at 1 14 10 pm" src="https://cloud.githubusercontent.com/assets/466585/13020510/a7d8df3e-d18a-11e5-86da-6d2a9361d383.png">

now:
<img width="333" alt="screen shot 2016-02-12 at 1 14 14 pm" src="https://cloud.githubusercontent.com/assets/466585/13020517/b25d52b4-d18a-11e5-8df5-f8e21ab5bec5.png">

**Comment by sensescape** [comment]
Looks like it doubled in line-width. Where do I adjust the line-width?

**Comment by patriciogonzalezvivo** [comment]
I just push a fix... Is less efficient but more flexible

**Comment by sensescape** [comment]
nice! thank you! looks amazing

**Comment by patriciogonzalezvivo** [comment]
:+1:   : D    :+1:

**Comment by sensescape** [comment]
this is fixed

**Comment by patriciogonzalezvivo** [comment]
yay

**Comment by sensescape** [comment]
yay!
